# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: mysql2
  database: development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: your password
test:
  adapter: mysql2
  database: test
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: your password

production:
  adapter: mysql2
  database: production
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: your password